AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB Table for Chat App Messages

Resources:
  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ChatMessages
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: TimestampIndex
          KeySchema:
            - AttributeName: id
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

Outputs:
  TableName:
    Value: !Ref MessagesTable
  TableArn:
    Value: !GetAtt MessagesTable.Arn
